[package]
name = "csvizmo-depgraph"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

description = "Dependency graph utilities"

[dependencies]

[dev-dependencies]
