[package]
name = "isobus"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "A code representation of the https://isobus.net/isobus/ database"

[dependencies]

[build-dependencies]
isobus-gen = { path = "../isobus-gen" }
