[package]
name = "csvizmo-test"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
assert_cmd.workspace = true
eyre.workspace = true
tempfile.workspace = true
